# Generated by Django 3.1.1 on 2020-12-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201229_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categpry',
            new_name='category',
        ),
    ]
